# Generated by Django 5.2.14 on 2026-05-27 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('one_time_price', 'One-time'), ('recurring_price', 'Recurring')], default='one_time_price', max_length=32)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('boost_for_days', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('unlocks_publish', models.BooleanField(default=False)),
                ('payment_frequency_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payment_frequency_interval', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=16)),
                ('subscription_period_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('subscription_period_interval', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=16)),
            ],
            options={
                'ordering': ('price_cents', 'name'),
                'indexes': [models.Index(fields=['type', 'price_cents'], name='billing_pla_type_fcdb82_idx'), models.Index(fields=['is_active', 'unlocks_publish', 'price_cents'], name='billing_pla_is_acti_1c79c0_idx'), models.Index(fields=['external_id'], name='billing_pla_externa_090041_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='billing_plan_single_default_plan')],
            },
        ),
    ]
