# Generated by Django 5.2.12 on 2026-03-30 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paddle', 'Paddle'), ('dodo', 'Dodo'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='pending', max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('provider_account_id', models.CharField(blank=True, max_length=160)),
                ('external_reference', models.CharField(blank=True, max_length=160)),
                ('dashboard_url', models.URLField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_connector', to='catalog.product')),
            ],
            options={
                'ordering': ('product__name',),
            },
        ),
        migrations.CreateModel(
            name='PaymentConnectorCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('rotating', 'Rotating'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='billing.paymentconnector')),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='PaymentRevenueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_on', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('recurring_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('all_time_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active_customers', models.PositiveIntegerField(default=0)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_snapshots', to='billing.paymentconnector')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_snapshots', to='catalog.product')),
            ],
            options={
                'ordering': ('-captured_on',),
                'constraints': [models.UniqueConstraint(fields=('connector', 'captured_on'), name='unique_revenue_snapshot_per_connector_day'), models.CheckConstraint(condition=models.Q(('period_start__isnull', True), ('period_end__isnull', True), ('period_end__gte', models.F('period_start')), _connector='OR'), name='payment_snapshot_period_range_valid')],
            },
        ),
        migrations.CreateModel(
            name='UserPlanPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=160)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='catalog.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-starts_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='user_plan_purchase_date_range_valid')],
            },
        ),
    ]
