# Generated by Django 5.2.14 on 2026-05-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='plan',
            name='billing_pla_is_acti_1c79c0_idx',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='unlocks_publish',
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active', 'price_cents'], name='billing_pla_is_acti_bc7e57_idx'),
        ),
    ]
