# Generated by Django 5.2.14 on 2026-05-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_plan_billing_pla_is_acti_1c79c0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='currency_code',
        ),
    ]
