import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, '.'),
    },
  },
  test: {
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.tsx'],
    globals: true,
    coverage: {
      provider: 'v8',
      reportsDirectory: './coverage',
      reporter: ['text', 'html', 'lcov'],
      // Cover library, hooks, atoms, and a widened set of molecules
      include: [
        'lib/**/*',
        'hooks/**/*',
        // Curated atoms set
        'components/atoms/badge.tsx',
        'components/atoms/button.tsx',
        'components/atoms/input.tsx',
        'components/atoms/label.tsx',
        'components/atoms/textarea.tsx',
        'components/atoms/accordion.tsx',
        'components/atoms/tooltip.tsx',
        'components/atoms/avatar.tsx',
        'components/atoms/skeleton.tsx',
        'components/atoms/card.tsx',
        'components/atoms/separator.tsx',
        'components/atoms/checkbox.tsx',
        'components/atoms/switch.tsx',
        'components/atoms/scroll-area.tsx',
        // Widen to additional molecules (keep expanding iteratively)
        'components/molecules/CopyButton.tsx',
        'components/molecules/ExternalBadgeLink.tsx',
        'components/molecules/MemberAreaButton.tsx',
        'components/molecules/SignInCtaButton.tsx',
        'components/molecules/ShareOnXButton.tsx',
        'components/molecules/ShareOnX.tsx',
        'components/molecules/AddButton.tsx',
        'components/molecules/SignOutCtaButton.tsx',
        'components/molecules/PageHeader.tsx',
        'components/molecules/PageSectionHeader.tsx',
        'components/molecules/PricingFeature.tsx',
        'components/molecules/BreadCrumbs.tsx',
        'components/molecules/CategoryIcons.tsx',
        'components/molecules/Relationship.tsx',
        'components/molecules/CreateButton.tsx',
        'components/molecules/DeleteButton.tsx',
        'components/molecules/ArchiveButton.tsx',
        'components/molecules/UnarchiveButton.tsx',
        'components/molecules/PublishButton.tsx',
        'components/molecules/UnpublishButton.tsx',
        'components/molecules/VerifyDomainButton.tsx',
        'components/molecules/SubmitProductButton.tsx',
        'components/molecules/UniformCard.tsx',
        'components/molecules/StatCard.tsx',
        'components/molecules/CategoryCard.tsx',
        'components/molecules/ProductAuthor.tsx',
        'components/molecules/ProductList.tsx',
        'components/molecules/ProductCard.tsx',
        'components/molecules/PerformanceCard.tsx',
        'components/molecules/PricingCard.tsx',
        // Organisms (lightweight sections)
        'components/organisms/HomepageSpotlight.tsx',
        'components/organisms/LatestLaunches.tsx',
        'components/organisms/PricingTable.tsx',
        'components/organisms/CategoryFeatured.tsx',
        'components/organisms/FeaturedHighlights.tsx',
        'components/organisms/LandingHero.tsx',
        'components/molecules/CTAFeatureYourProductCard.tsx',
        'components/molecules/UpvoteSquare.tsx',
        'components/molecules/InlineSelect.tsx',
      ],
      exclude: [
        'node_modules/**',
        '.next/**',
        'prisma/**',
        'next.config.ts',
        'postcss.config.mjs',
        'tailwind.config.js',
        'eslint.config.mjs',
        '**/*.d.ts',
        // Exclude some complex client-heavy molecules for now; we will expand later
        'components/molecules/DataTable.tsx',
        'components/molecules/ProductMediaManager.tsx',
        'components/molecules/ProductGridClient.tsx',
        'components/molecules/ProductWizardStepRenderer.tsx',
      ],
    },
  },
});
