# Generated by Django 5.2.12 on 2026-03-30 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTrafficDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(unique=True)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('signups', models.PositiveIntegerField(default=0)),
                ('pageviews', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-day',),
            },
        ),
        migrations.CreateModel(
            name='LeaderboardRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_label', models.CharField(max_length=80)),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-period_end',),
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='leaderboard_run_period_range_valid')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsIngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('posthog', 'PostHog'), ('plausible', 'Plausible'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('job', models.CharField(choices=[('product-sync', 'Product sync'), ('site-sync', 'Site sync'), ('leaderboard', 'Leaderboard')], default='product-sync', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_ingestions', to='catalog.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='analytics_ingestion_run_date_range_valid')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyLeaderboardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('leaderboard_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='analytics.leaderboardrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('leaderboard_run', 'user'), name='unique_leaderboard_notification_per_user')],
            },
        ),
        migrations.CreateModel(
            name='ProductLeaderboardScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('leaderboard_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='analytics.leaderboardrun')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_scores', to='catalog.product')),
            ],
            options={
                'ordering': ('rank', 'product__name'),
                'constraints': [models.UniqueConstraint(fields=('leaderboard_run', 'product'), name='unique_score_per_run_product'), models.UniqueConstraint(fields=('leaderboard_run', 'rank'), name='unique_score_rank_per_run')],
            },
        ),
        migrations.CreateModel(
            name='ProductTrafficDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('signups', models.PositiveIntegerField(default=0)),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_daily', to='catalog.product')),
            ],
            options={
                'ordering': ('-day',),
                'constraints': [models.UniqueConstraint(fields=('product', 'day'), name='unique_product_daily_traffic')],
            },
        ),
    ]
