from django.urls import path

from catalog.views_public import (
    AlternativeDetailView,
    AlternativesListView,
    BrowseView,
    CategoryDetailView,
    CategoryListView,
    CategoryPlatformView,
    CategoryPricingView,
    HomeView,
    LegalPrivacyView,
    LegalTermsView,
    PlatformDetailView,
    PricingDetailView,
    PricingListView,
    ProductDetailView,
    ProductTypeDetailView,
    RedirectLinkView,
    TagDetailView,
    TagsListView,
    UseCaseDetailView,
    UseCaseListView,
    UserDetailView,
    UsersListView,
    WhyShipyardView,
)

app_name = "public"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("browse", BrowseView.as_view(), name="browse"),
    path("products/<slug:slug>", ProductDetailView.as_view(), name="product-detail"),
    path("categories", CategoryListView.as_view(), name="categories"),
    path("categories/<slug:slug>", CategoryDetailView.as_view(), name="category-detail"),
    path(
        "categories/<slug:slug>/pricing/<slug:pricing_model>",
        CategoryPricingView.as_view(),
        name="category-pricing",
    ),
    path(
        "categories/<slug:slug>/platforms/<slug:platform>",
        CategoryPlatformView.as_view(),
        name="category-platform",
    ),
    path("pricing", PricingListView.as_view(), name="pricing"),
    path("pricing/<slug:pricing_model>", PricingDetailView.as_view(), name="pricing-detail"),
    path(
        "product-types/<slug:product_type>",
        ProductTypeDetailView.as_view(),
        name="product-type-detail",
    ),
    path("platforms/<slug:platform>", PlatformDetailView.as_view(), name="platform-detail"),
    path("use-cases", UseCaseListView.as_view(), name="use-cases"),
    path("use-cases/<slug:slug>", UseCaseDetailView.as_view(), name="use-case-detail"),
    path("alternatives", AlternativesListView.as_view(), name="alternatives"),
    path("alternatives/<slug:slug>", AlternativeDetailView.as_view(), name="alternative-detail"),
    path("tags", TagsListView.as_view(), name="tags"),
    path("tags/<slug:slug>", TagDetailView.as_view(), name="tag-detail"),
    path("users", UsersListView.as_view(), name="users"),
    path("users/<str:user_ref>", UserDetailView.as_view(), name="user-detail"),
    path("why-shipyard", WhyShipyardView.as_view(), name="why-shipyard"),
    path("legal/privacy-policy", LegalPrivacyView.as_view(), name="legal-privacy"),
    path("legal/terms", LegalTermsView.as_view(), name="legal-terms"),
    path("r/<slug:slug>", RedirectLinkView.as_view(), name="redirect-product"),
    path("r/sponsored/<slug:slug>", RedirectLinkView.as_view(), name="redirect-sponsored"),
    path("r/sticky-banner/<slug:slug>", RedirectLinkView.as_view(), name="redirect-sticky-banner"),
]
