-- Remove the retired analytics rollups before narrowing their source enum.
DELETE FROM "ProductTrafficBrowserDaily" WHERE "source" = 'ga4';
DELETE FROM "ProductTrafficOperatingSystemDaily" WHERE "source" = 'ga4';
DELETE FROM "ProductTrafficDeviceDaily" WHERE "source" = 'ga4';
DELETE FROM "ProductTrafficCountryDaily" WHERE "source" = 'ga4';
DELETE FROM "ProductTrafficCityDaily" WHERE "source" = 'ga4';
DELETE FROM "ProductTrafficDaily" WHERE "source" = 'ga4';
DELETE FROM "SiteTrafficBrowserDaily" WHERE "source" = 'ga4';
DELETE FROM "SiteTrafficOperatingSystemDaily" WHERE "source" = 'ga4';
DELETE FROM "SiteTrafficDeviceDaily" WHERE "source" = 'ga4';
DELETE FROM "SiteTrafficCountryDaily" WHERE "source" = 'ga4';
DELETE FROM "SiteTrafficRegionDaily" WHERE "source" = 'ga4';
DELETE FROM "SiteTrafficCityDaily" WHERE "source" = 'ga4';
DELETE FROM "SiteTrafficHourly" WHERE "source" = 'ga4';
DELETE FROM "SiteTrafficCompositionDaily" WHERE "source" = 'ga4';
DELETE FROM "SiteAiCrawlerStatusDaily" WHERE "source" = 'ga4';
DELETE FROM "SiteAiCrawlerEndpointDaily" WHERE "source" = 'ga4';
DELETE FROM "SiteTrafficDaily" WHERE "source" = 'ga4';
DELETE FROM "AnalyticsIngestionRun" WHERE "source" = 'ga4';

ALTER TABLE "AnalyticsIngestionRun" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "ProductTrafficDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "ProductTrafficBrowserDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "ProductTrafficOperatingSystemDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "ProductTrafficDeviceDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "ProductTrafficCountryDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "ProductTrafficCityDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "SiteTrafficDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "SiteTrafficHourly" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "SiteTrafficCompositionDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "SiteAiCrawlerStatusDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "SiteAiCrawlerEndpointDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "SiteTrafficBrowserDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "SiteTrafficOperatingSystemDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "SiteTrafficDeviceDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "SiteTrafficCountryDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "SiteTrafficRegionDaily" ALTER COLUMN "source" DROP DEFAULT;
ALTER TABLE "SiteTrafficCityDaily" ALTER COLUMN "source" DROP DEFAULT;

ALTER TYPE "AnalyticsDataSource" RENAME TO "AnalyticsDataSource_legacy";
CREATE TYPE "AnalyticsDataSource" AS ENUM ('cloudflare');

ALTER TABLE "AnalyticsIngestionRun" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "ProductTrafficDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "ProductTrafficBrowserDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "ProductTrafficOperatingSystemDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "ProductTrafficDeviceDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "ProductTrafficCountryDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "ProductTrafficCityDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "SiteTrafficDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "SiteTrafficHourly" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "SiteTrafficCompositionDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "SiteAiCrawlerStatusDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "SiteAiCrawlerEndpointDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "SiteTrafficBrowserDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "SiteTrafficOperatingSystemDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "SiteTrafficDeviceDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "SiteTrafficCountryDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "SiteTrafficRegionDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");
ALTER TABLE "SiteTrafficCityDaily" ALTER COLUMN "source" TYPE "AnalyticsDataSource" USING ("source"::text::"AnalyticsDataSource");

ALTER TABLE "AnalyticsIngestionRun" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "ProductTrafficDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "ProductTrafficBrowserDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "ProductTrafficOperatingSystemDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "ProductTrafficDeviceDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "ProductTrafficCountryDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "ProductTrafficCityDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "SiteTrafficDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "SiteTrafficHourly" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "SiteTrafficCompositionDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "SiteAiCrawlerStatusDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "SiteAiCrawlerEndpointDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "SiteTrafficBrowserDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "SiteTrafficOperatingSystemDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "SiteTrafficDeviceDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "SiteTrafficCountryDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "SiteTrafficRegionDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';
ALTER TABLE "SiteTrafficCityDaily" ALTER COLUMN "source" SET DEFAULT 'cloudflare';

DROP TYPE "AnalyticsDataSource_legacy";
