import { TREND_RADAR_CATEGORY_LIMIT } from "@/lib/trend-radar"

export const HOMEPAGE_CATEGORY_RAIL_LIMIT = 8

export const HOMEPAGE_TOP_CATEGORY_LIMIT = Math.max(
  HOMEPAGE_CATEGORY_RAIL_LIMIT,
  TREND_RADAR_CATEGORY_LIMIT,
)

export { TREND_RADAR_CATEGORY_LIMIT }
