import { PageHeader } from "@/components/molecules/PageHeader"
import { CoreStructuredData } from "@/components/seo/CoreStructuredData"
import { BRAND_NAME } from "@/lib/brand"
import { buildPageMetadata } from "@/lib/metadata"
import { HOME_PATH, LEGAL_PATH, LEGAL_PRIVACY_PATH } from "@/lib/routes"

const PAGE_TITLE = "Privacy Policy"

export const metadata = buildPageMetadata({
  title: PAGE_TITLE,
  description: `Learn how ${BRAND_NAME} collects, uses, and protects your personal information.`,
  canonical: LEGAL_PRIVACY_PATH,
})

export default function PrivacyPolicyPage() {
  return (
    <>
      <CoreStructuredData
        scriptKeyPrefix="privacy"
        webPage={{ path: LEGAL_PRIVACY_PATH, name: PAGE_TITLE }}
        breadcrumbs={{
          items: [
            { name: "Home", path: HOME_PATH },
            { name: "Legal", path: LEGAL_PATH },
            { name: PAGE_TITLE, path: LEGAL_PRIVACY_PATH },
          ],
        }}
      />
      <div className="min-h-screen py-16">
        <div className="mx-auto max-w-3xl px-4 md:px-8">
          <PageHeader
            title="Privacy Policy"
            subtitle={`Learn how ${BRAND_NAME} collects, uses, and protects your personal information.`}
          />
          <div className="mt-6 space-y-6">
            <p className="text-muted-foreground">Last updated: Jul 22, 2026</p>

            <p>
              {BRAND_NAME} builds tools that help independent founders and
              product teams launch, promote, and measure their products. This
              Privacy Policy explains what information we collect, how we use
              and share it, and the choices you have. By using {BRAND_NAME}, you
              agree to this policy. If you do not agree, please do not access
              the service.
            </p>

            <h2 className="text-2xl font-semibold mt-6">
              Information We Collect
            </h2>
            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-semibold">
                  Information you provide
                </h3>
                <ul className="list-disc list-inside space-y-2">
                  <li>
                    <strong>Account and profile data:</strong> Name, email,
                    photo, and authentication details supplied through Clerk,
                    plus optional information such as job title, role
                    preferences, and onboarding responses.
                  </li>
                  <li>
                    <strong>Product and workspace content:</strong> Product
                    names, descriptions, categories, pricing details, media
                    assets, metadata links, campaign notes, and other material
                    you submit to {BRAND_NAME}.
                  </li>
                  <li>
                    <strong>Transactions and plans:</strong> Plan selections,
                    feature access, and limited billing metadata associated with
                    purchases initiated through Dodo Payments. Card details are
                    handled directly by Dodo—we do not store full payment
                    instrument numbers.
                  </li>
                  <li>
                    <strong>Community interactions:</strong> Reviews, upvotes,
                    feedback messages, support requests, and surveys.
                  </li>
                </ul>
              </div>

              <div>
                <h3 className="text-lg font-semibold">
                  Information collected automatically
                </h3>
                <ul className="list-disc list-inside space-y-2">
                  <li>
                    <strong>Analytics signals:</strong> Page views, links you
                    click, engagement with placements, and other in-product
                    actions. Traffic events record device type, browser,
                    operating system, referrer, and coarse geolocation (country,
                    region, and city) derived from request headers.
                  </li>
                  <li>
                    <strong>Network data:</strong> We hash IP addresses using a
                    salted HMAC before storing them so we can detect abuse and
                    build aggregate analytics without keeping plain IPs.
                  </li>
                  <li>
                    <strong>Technical logs:</strong> Diagnostic log entries,
                    error traces, and performance metrics generated by the
                    self-hosted infrastructure that runs {BRAND_NAME}.
                  </li>
                  <li>
                    <strong>Advertising signals:</strong> When display
                    advertising is enabled on eligible guide pages, Google and
                    its advertising partners may process cookie identifiers,
                    device information, approximate location, ad interactions,
                    and page context to deliver, limit, and measure ads.
                  </li>
                </ul>
              </div>

              <div>
                <h3 className="text-lg font-semibold">
                  Information from other sources
                </h3>
                <ul className="list-disc list-inside space-y-2">
                  <li>
                    Authentication, profile, and security signals received from
                    Clerk so we can verify your account.
                  </li>
                  <li>
                    Billing status, checkout events, and payment confirmations
                    provided by Dodo Payments when you purchase a plan or redeem
                    a perk.
                  </li>
                  <li>
                    AI service outputs from OpenAI when you opt into features
                    such as product autofill, analytics narratives, or social
                    copy generation. We send only the data required to fulfil
                    the request.
                  </li>
                  <li>
                    Publicly available information about your product gathered
                    by {BRAND_NAME} for onboarding (for example, parsing a
                    public marketing site you ask us to analyze).
                  </li>
                </ul>
              </div>
            </div>

            <h2 className="text-2xl font-semibold mt-6">
              How We Use Information
            </h2>
            <ul className="list-disc list-inside space-y-2">
              <li>Operate, maintain, and secure the {BRAND_NAME} platform.</li>
              <li>Publish product listings and dashboards you create.</li>
              <li>
                Process transactions, deliver perks, and provide billing
                support.
              </li>
              <li>
                Generate analytics, insights, and automated suggestions to help
                you understand performance.
              </li>
              <li>
                Communicate with you about your account, respond to requests,
                and send optional marketing updates (you can opt out at any
                time).
              </li>
              <li>
                Monitor usage, prevent fraud or abuse, and enforce our Terms of
                Service.
              </li>
              <li>
                Research, develop, and improve new products, features, and
                automation tools.
              </li>
              <li>
                Comply with applicable law, legal requests, and regulatory
                obligations.
              </li>
            </ul>

            <h2 className="text-2xl font-semibold mt-6">
              Legal Bases (EEA &amp; UK Users)
            </h2>
            <p>
              Where required, we rely on one or more of the following legal
              bases to process personal data: (i) performance of a contract
              (providing the service you signed up for); (ii) our legitimate
              interests (for example, securing the platform, understanding
              product usage, and improving features); (iii) your consent (for
              marketing messages or optional AI features); and (iv) compliance
              with legal obligations.
            </p>

            <h2 className="text-2xl font-semibold mt-6">
              How We Share Information
            </h2>
            <ul className="list-disc list-inside space-y-2">
              <li>
                <strong>Service providers:</strong> We partner with vendors who
                support hosting, authentication, email delivery, analytics, AI
                processing, file storage, and payments. Key providers include
                our infrastructure providers (hosting and file storage), Clerk
                (identity management), OpenAI (AI features), Dodo Payments
                (billing), and Google AdSense (advertising on eligible
                publisher-authored pages).
              </li>
              <li>
                <strong>Teams and community:</strong> Content you publish—such
                as product listings, reviews, and leaderboard standings—is
                visible to other users by design.
              </li>
              <li>
                <strong>Business transfers:</strong> In connection with a
                merger, acquisition, financing, or sale of assets, your
                information may be disclosed as part of the transaction.
              </li>
              <li>
                <strong>Legal obligations:</strong> We may disclose information
                if we believe it is reasonably necessary to comply with law,
                protect our rights, investigate fraud, or respond to lawful
                requests from public authorities.
              </li>
            </ul>
            <p>We never sell your personal information.</p>

            <h2 className="text-2xl font-semibold mt-6">
              Advertising, Cookies, and Your Choices
            </h2>
            <div className="space-y-4">
              <p>
                {BRAND_NAME} may use Google AdSense to show display ads on
                substantial publisher-authored guide pages. We do not place
                these ads inside maker profiles, product-submitted descriptions,
                directory feeds, or search results. Google may use cookies or
                similar technologies to deliver and measure ads, subject to your
                location, consent choices, and Google&apos;s settings.
              </p>
              <p>
                You can learn how Google uses information from sites that use
                its services in Google&apos;s{" "}
                <a
                  href="https://policies.google.com/technologies/partner-sites"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary underline"
                >
                  partner sites notice
                </a>
                , review its{" "}
                <a
                  href="https://policies.google.com/technologies/ads"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary underline"
                >
                  advertising policy explanation
                </a>
                , and manage advertising preferences in{" "}
                <a
                  href="https://adssettings.google.com/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary underline"
                >
                  Google&apos;s ad settings
                </a>
                . You can also restrict cookies through your browser. Blocking
                advertising cookies may change the ads you see but should not
                prevent access to Shipyard&apos;s public content.
              </p>
            </div>

            <h2 className="text-2xl font-semibold mt-6">
              AI-Facilitated Features
            </h2>
            <p>
              {BRAND_NAME} offers optional AI tooling (such as product autofill,
              analytics narratives, and launch copy suggestions). When you use
              these features we send the minimum viable prompt data—often
              product metadata or aggregated analytics—to OpenAI. Outputs may
              contain inaccuracies, so you should review them before publishing.
              We do not permit OpenAI to train on your prompts or outputs.
            </p>

            <h2 className="text-2xl font-semibold mt-6">
              Your Rights and Choices
            </h2>
            <ul className="list-disc list-inside space-y-2">
              <li>
                Access, update, or delete profile information from your account
                settings or by emailing{" "}
                <a
                  href="mailto:support@shipyardhq.dev"
                  className="text-primary underline"
                >
                  support@shipyardhq.dev
                </a>
                .
              </li>
              <li>
                Export or delete your data by submitting a support request. We
                may retain certain records where required by law or for
                legitimate business purposes.
              </li>
              <li>
                Manage marketing preferences using the unsubscribe link in any
                email or by contacting us.
              </li>
              <li>
                Adjust browser or device settings to control cookies and other
                tracking technologies. Core functionality may require essential
                cookies.
              </li>
            </ul>

            <h2 className="text-2xl font-semibold mt-6">Data Retention</h2>
            <p>
              We keep personal information for as long as it is needed to
              deliver the service, fulfill the purposes outlined above, or
              comply with legal obligations. When data is no longer required, we
              delete or de-identify it according to our retention schedules.
            </p>

            <h2 className="text-2xl font-semibold mt-6">Security</h2>
            <p>
              We use administrative, technical, and organizational measures to
              protect your information, including account access controls,
              encrypted transport (HTTPS), salted IP hashing, and restricted
              data access for employees and contractors. No system is perfectly
              secure, so please report suspected incidents to us immediately.
            </p>

            <h2 className="text-2xl font-semibold mt-6">
              International Data Transfers
            </h2>
            <p>
              {BRAND_NAME} operates from the United States. If you access the
              service from another region, your information may be transferred
              to, stored, and processed in the U.S. or other countries where our
              vendors operate. We implement appropriate safeguards, such as
              contractual data protection terms, for cross-border transfers.
            </p>

            <h2 className="text-2xl font-semibold mt-6">
              Children&apos;s Privacy
            </h2>
            <p>
              {BRAND_NAME} is not directed to children under 18, and we do not
              knowingly collect personal information from them. If we learn that
              a minor under 18 has provided personal data, we will delete it.
            </p>

            <h2 className="text-2xl font-semibold mt-6">Changes</h2>
            <p>
              We may update this Privacy Policy to reflect operational, legal,
              or regulatory developments. When we make material changes we will
              update the date at the top of this page and, where appropriate,
              provide additional notice.
            </p>

            <h2 id="contact" className="text-2xl font-semibold mt-6">
              Contact Us
            </h2>
            <p>
              Questions or requests? Email{" "}
              <a
                href="mailto:support@shipyardhq.dev"
                className="text-primary underline"
              >
                support@shipyardhq.dev
              </a>
              .
            </p>
          </div>
        </div>
      </div>
    </>
  )
}
