# Generated by Django 5.2.12 on 2026-03-30 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('hero_title', models.CharField(blank=True, max_length=160)),
                ('seo_summary', models.CharField(blank=True, max_length=260)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('enterprise', 'Enterprise')], default='paid', max_length=20)),
                ('interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year'), ('lifetime', 'Lifetime')], default='month', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('category', models.CharField(choices=[('visibility', 'Visibility'), ('analytics', 'Analytics'), ('trust', 'Trust'), ('growth', 'Growth')], default='visibility', max_length=30)),
                ('feature_key', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('hero_title', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('website_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('banner_image_url', models.URLField(blank=True)),
                ('product_type', models.CharField(choices=[('saas', 'SaaS'), ('api', 'API'), ('service', 'Service'), ('community', 'Community')], default='saas', max_length=20)),
                ('pricing_model', models.CharField(choices=[('free', 'Free'), ('freemium', 'Freemium'), ('paid', 'Paid'), ('custom', 'Custom')], default='freemium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('ios', 'iOS'), ('android', 'Android'), ('desktop', 'Desktop'), ('api', 'API')], default='web', max_length=20)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('external_subscription_id', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('plan_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('starting_price_cents', models.PositiveIntegerField(default=0)),
                ('currency_code', models.CharField(default='USD', max_length=10)),
                ('featured', models.BooleanField(default=False)),
                ('launched_on', models.DateField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='catalog.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.plan')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='catalog.tag')),
                ('use_cases', models.ManyToManyField(blank=True, related_name='products', to='catalog.usecase')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MemberFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='catalog.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AlternativeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('summary', models.CharField(blank=True, max_length=220)),
                ('website_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='alternative_products', to='catalog.category')),
                ('products', models.ManyToManyField(blank=True, related_name='alternative_products', to='catalog.product')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_visitors', models.PositiveIntegerField(default=0)),
                ('monthly_signups', models.PositiveIntegerField(default=0)),
                ('monthly_pageviews', models.PositiveIntegerField(default=0)),
                ('verified_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductClaimAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('email', 'Email'), ('domain', 'Domain'), ('payment', 'Payment')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('proof_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_claim_attempts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_attempts', to='catalog.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_product_claim_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headquarters', models.CharField(blank=True, max_length=120)),
                ('founder_name', models.CharField(blank=True, max_length=120)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_url', models.URLField(blank=True)),
                ('pricing_page_url', models.URLField(blank=True)),
                ('setup_time', models.CharField(blank=True, max_length=80)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('integrations', models.JSONField(blank=True, default=list)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='catalog.product')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UseCaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_case_assignments', to='catalog.category')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='catalog.usecase')),
            ],
            options={
                'ordering': ('sort_order', 'category__name'),
            },
        ),
        migrations.CreateModel(
            name='PlanFeatureAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, max_length=120)),
                ('highlighted', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assignments', to='catalog.planfeature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_assignments', to='catalog.plan')),
            ],
            options={
                'ordering': ('sort_order', 'feature__name'),
                'constraints': [models.UniqueConstraint(fields=('plan', 'feature'), name='unique_plan_feature_assignment')],
            },
        ),
        migrations.CreateModel(
            name='ProductBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=220)),
                ('color_token', models.CharField(default='steel', max_length=40)),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='catalog.product')),
            ],
            options={
                'ordering': ('label',),
                'constraints': [models.CheckConstraint(condition=models.Q(('active_from__isnull', True), ('active_until__isnull', True), ('active_until__gte', models.F('active_from')), _connector='OR'), name='product_badge_date_range_valid')],
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('logo', 'Logo')], default='image', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('asset_url', models.URLField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.product')),
            ],
            options={
                'ordering': ('sort_order', 'title'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_media_per_product')],
            },
        ),
        migrations.CreateModel(
            name='ProductUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('product', 'user'), name='unique_product_upvote')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'name'], name='catalog_pro_status_df35cc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['owner', 'status'], name='catalog_pro_owner_i_9bf3a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='usecasecategory',
            constraint=models.UniqueConstraint(fields=('use_case', 'category'), name='unique_use_case_category'),
        ),
    ]
