# Generated by Django 5.2.14 on 2026-05-27 06:02

import django.contrib.postgres.indexes
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('extras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='platform',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.pricingmodel'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='productalternativeassignment',
            name='alternative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_for_assignments', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productalternativeassignment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_assignments', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productlink',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productplatformassignment',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_assignments', to='catalog.platform'),
        ),
        migrations.AddField(
            model_name='productplatformassignment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_assignments', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.producttype'),
        ),
        migrations.AddField(
            model_name='productusecaseassignment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_case_assignments', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='productusecaseassignment',
            name='use_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_assignments', to='catalog.usecase'),
        ),
        migrations.AddField(
            model_name='usecasecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_case_links', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='usecasecategory',
            name='use_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='catalog.usecase'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='use_cases', through='catalog.UseCaseCategory', to='catalog.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active', 'name'], name='catalog_cat_parent__73b1ce_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug', 'is_active'], name='catalog_cat_slug_f4b9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='productalternativeassignment',
            index=models.Index(fields=['product', 'alternative', 'id'], name='catalog_pro_product_de1133_idx'),
        ),
        migrations.AddIndex(
            model_name='productalternativeassignment',
            index=models.Index(fields=['alternative', 'product'], name='catalog_pro_alterna_bec0a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='productalternativeassignment',
            constraint=models.UniqueConstraint(fields=('product', 'alternative'), name='catalog_productalternativeassignment_unique_product_alternative'),
        ),
        migrations.AddConstraint(
            model_name='productalternativeassignment',
            constraint=models.CheckConstraint(condition=models.Q(('product', models.F('alternative')), _negated=True), name='catalog_productalternativeassignment_prevent_self_alternative'),
        ),
        migrations.AddIndex(
            model_name='productlink',
            index=models.Index(fields=['product', 'link_type', 'is_primary', 'id'], name='catalog_pro_product_a37ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['product', 'media_type', 'created', 'id'], name='catalog_pro_product_6f4b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='productplatformassignment',
            index=models.Index(fields=['platform', 'product', 'id'], name='catalog_pro_platfor_999486_idx'),
        ),
        migrations.AddIndex(
            model_name='productplatformassignment',
            index=models.Index(fields=['product', 'platform'], name='catalog_pro_product_256dc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='productplatformassignment',
            constraint=models.UniqueConstraint(fields=('product', 'platform'), name='catalog_productplatformassignment_unique_product_platform'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'published_at'], name='catalog_pro_status_4a4a51_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_listed', 'status', 'published_at'], name='catalog_pro_is_list_3bfeb7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status', 'published_at'], name='catalog_pro_categor_00e4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['pricing_model', 'status', 'published_at'], name='catalog_pro_pricing_847862_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'status', 'published_at'], name='catalog_pro_product_389549_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='catalog_pro_search__ef5de3_gin'),
        ),
        migrations.AddIndex(
            model_name='productusecaseassignment',
            index=models.Index(fields=['use_case', 'product', 'id'], name='catalog_pro_use_cas_80bddc_idx'),
        ),
        migrations.AddIndex(
            model_name='productusecaseassignment',
            index=models.Index(fields=['product', 'use_case'], name='catalog_pro_product_d14d4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='productusecaseassignment',
            constraint=models.UniqueConstraint(fields=('product', 'use_case'), name='catalog_productusecaseassignment_unique_product_use_case'),
        ),
        migrations.AddIndex(
            model_name='usecasecategory',
            index=models.Index(fields=['category', 'use_case'], name='catalog_use_categor_95053c_idx'),
        ),
        migrations.AddIndex(
            model_name='usecasecategory',
            index=models.Index(fields=['use_case', 'category'], name='catalog_use_use_cas_347ba2_idx'),
        ),
        migrations.AddConstraint(
            model_name='usecasecategory',
            constraint=models.UniqueConstraint(fields=('use_case', 'category'), name='unique_use_case_category'),
        ),
    ]
