# Generated by Django 5.2.14 on 2026-05-27 06:27

import django.db.models.deletion
from django.db import migrations, models


def copy_product_categories(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    ProductCategoryAssignment = apps.get_model("catalog", "ProductCategoryAssignment")
    db_alias = schema_editor.connection.alias

    assignments = [
        ProductCategoryAssignment(product_id=product.pk, category_id=product.category_id)
        for product in Product.objects.using(db_alias).exclude(category_id=None).only("id", "category_id")
    ]
    ProductCategoryAssignment.objects.using(db_alias).bulk_create(assignments, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('category', 'product', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='productcategoryassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_assignments', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='productcategoryassignment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='catalog.product'),
        ),
        migrations.RunPython(copy_product_categories, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_categor_00e4f6_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddIndex(
            model_name='productcategoryassignment',
            index=models.Index(fields=['category', 'product', 'id'], name='catalog_pro_categor_47997a_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategoryassignment',
            index=models.Index(fields=['product', 'category'], name='catalog_pro_product_4cfde6_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcategoryassignment',
            constraint=models.UniqueConstraint(fields=('product', 'category'), name='catalog_productcategoryassignment_unique_product_category'),
        ),
    ]
