# Generated by Django 5.2.14 on 2026-05-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('bolt', 'Bolt'), ('code', 'Code'), ('cloud', 'Cloud'), ('robot', 'Robot'), ('chart', 'Chart'), ('tool', 'Tool'), ('cursor', 'Cursor'), ('message', 'Message'), ('database', 'Database'), ('shield', 'Shield'), ('brain', 'AI / Brain'), ('flask', 'Beta / Flask'), ('users', 'Users / Community'), ('devices', 'Devices'), ('palette', 'Palette / Design'), ('wrench', 'Wrench / DIY'), ('school', 'School / Education'), ('coins', 'Coins / Finance'), ('gamepad', 'Gamepad / Gaming'), ('leaf', 'Leaf / Green'), ('heartbeat', 'Heartbeat / Health'), ('home', 'Home / Living'), ('briefcase', 'Briefcase / HR'), ('wifi', 'Wi-Fi / IoT'), ('scale', 'Scale / Legal'), ('megaphone', 'Megaphone / Marketing'), ('car', 'Car / Mobility'), ('music', 'Music / Audio'), ('handheart', 'Hand Heart / Impact'), ('checklist', 'Checklist / Productivity'), ('chefhat', 'Food & Beverage'), ('building', 'Building / Real Estate'), ('rocket', 'Rocket / Startup'), ('share', 'Share / Social'), ('plane', 'Plane / Travel'), ('video', 'Video / Creation'), ('hexagon', 'Hexagon / Web3'), ('target', 'Target / Sales'), ('map', 'Map / Tourism')], default='tool', max_length=32),
        ),
    ]
