# Generated by Django 5.2.14 on 2026-05-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductUseCaseAssignment',
        ),
    ]
