# Generated by Django 5.2.14 on 2026-05-27 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_use_case_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='starting_price_cents',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
