# Generated by Django 5.2.14 on 2026-05-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_currency_code_product_starting_price_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_badge_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='paid_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
