# Generated by Django 5.2.14 on 2026-05-27 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('catalog', '0007_product_paid_publish_checkout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='product',
            name='plan_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
