# Generated by Django 5.2.14 on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_plan_product_plan_assigned_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured_badge_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
