from django.urls import path

from . import views

urlpatterns = [
    path("", views.MemberHomeView.as_view(), name="member_home"),
    path("overview/", views.MemberOverviewView.as_view(), name="member_overview"),
    path("dashboard/", views.MemberDashboardRedirectView.as_view(), name="member_dashboard"),
    path("products/", views.MemberProductsView.as_view(), name="member_products"),
    path("products/autofill/", views.MemberProductAutofillView.as_view(), name="member_product_autofill"),
    path("products/add/", views.MemberProductAddView.as_view(), name="member_product_add"),
    path("products/<int:pk>/", views.MemberProductDetailView.as_view(), name="member_product"),
    path("products/<int:pk>/edit/", views.MemberProductEditView.as_view(), name="member_product_edit"),
    path("products/<int:pk>/delete/", views.MemberProductDeleteView.as_view(), name="member_product_delete"),
    path(
        "products/<int:pk>/media/<int:media_pk>/delete/",
        views.MemberProductMediaDeleteView.as_view(),
        name="member_product_media_delete",
    ),
    path("product-types/", views.MemberProductTypesView.as_view(), name="member_product_types"),
    path("product-types/add/", views.MemberProductTypeAddView.as_view(), name="member_product_type_add"),
    path("product-types/<int:pk>/", views.MemberProductTypeDetailView.as_view(), name="member_product_type"),
    path("product-types/<int:pk>/edit/", views.MemberProductTypeEditView.as_view(), name="member_product_type_edit"),
    path(
        "product-types/<int:pk>/delete/",
        views.MemberProductTypeDeleteView.as_view(),
        name="member_product_type_delete",
    ),
    path("pricing/", views.MemberPricingModelsView.as_view(), name="member_pricing_models"),
    path("pricing/add/", views.MemberPricingModelAddView.as_view(), name="member_pricing_model_add"),
    path("pricing/<int:pk>/", views.MemberPricingModelDetailView.as_view(), name="member_pricing_model"),
    path("pricing/<int:pk>/edit/", views.MemberPricingModelEditView.as_view(), name="member_pricing_model_edit"),
    path(
        "pricing/<int:pk>/delete/",
        views.MemberPricingModelDeleteView.as_view(),
        name="member_pricing_model_delete",
    ),
    path("platforms/", views.MemberPlatformsView.as_view(), name="member_platforms"),
    path("platforms/add/", views.MemberPlatformAddView.as_view(), name="member_platform_add"),
    path("platforms/<int:pk>/", views.MemberPlatformDetailView.as_view(), name="member_platform"),
    path("platforms/<int:pk>/edit/", views.MemberPlatformEditView.as_view(), name="member_platform_edit"),
    path("platforms/<int:pk>/delete/", views.MemberPlatformDeleteView.as_view(), name="member_platform_delete"),
    path("categories/", views.MemberCategoriesView.as_view(), name="member_categories"),
    path("categories/add/", views.MemberCategoryAddView.as_view(), name="member_category_add"),
    path("categories/<int:pk>/", views.MemberCategoryDetailView.as_view(), name="member_category"),
    path("categories/<int:pk>/edit/", views.MemberCategoryEditView.as_view(), name="member_category_edit"),
    path("categories/<int:pk>/delete/", views.MemberCategoryDeleteView.as_view(), name="member_category_delete"),
    path("use-cases/", views.MemberUseCasesView.as_view(), name="member_use_cases"),
    path("use-cases/add/", views.MemberUseCaseAddView.as_view(), name="member_use_case_add"),
    path("use-cases/<int:pk>/", views.MemberUseCaseDetailView.as_view(), name="member_use_case"),
    path("use-cases/<int:pk>/edit/", views.MemberUseCaseEditView.as_view(), name="member_use_case_edit"),
    path("use-cases/<int:pk>/delete/", views.MemberUseCaseDeleteView.as_view(), name="member_use_case_delete"),
    path("users/", views.MemberUsersView.as_view(), name="member_users"),
    path("users/<int:pk>/", views.MemberUserDetailView.as_view(), name="member_user"),
    path("users/<int:pk>/edit/", views.MemberUserEditView.as_view(), name="member_user_edit"),
    path("users/<int:pk>/delete/", views.MemberUserDeleteView.as_view(), name="member_user_delete"),
    path("launch/", views.MemberLaunchView.as_view(), name="member_launch"),
    path("profile/", views.MemberProfileView.as_view(), name="member_profile"),
]
