"""init

Revision ID: 1242533e7e1f
Revises: 
Create Date: 2026-01-23 21:24:00.287099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1242533e7e1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alternative_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('website_url')
    )
    op.create_index('ix_alternative_product_created_at', 'alternative_product', ['created_at'], unique=False)
    op.create_index('ix_alternative_product_updated_at', 'alternative_product', ['updated_at'], unique=False)
    op.create_table('analytics_ingestion_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('job', sa.Enum('PRODUCT_TRAFFIC_DAILY', 'PRODUCT_TRAFFIC_BREAKDOWNS', 'SITE_TRAFFIC_DAILY', 'SITE_TRAFFIC_BREAKDOWNS', name='analytics_ingestion_job_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analytics_ingestion_status_enum'), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'job', 'window_start', 'window_end', name='uq_analytics_ingestion_run')
    )
    op.create_index('ix_analytics_ingestion_run_job_source_window_start', 'analytics_ingestion_run', ['job', 'source', 'window_start'], unique=False)
    op.create_index('ix_analytics_ingestion_run_status_created_at', 'analytics_ingestion_run', ['status', 'created_at'], unique=False)
    op.create_index('ix_analytics_ingestion_run_window_start_end', 'analytics_ingestion_run', ['window_start', 'window_end'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_category_created_at', 'category', ['created_at'], unique=False)
    op.create_index('ix_category_updated_at', 'category', ['updated_at'], unique=False)
    op.create_table('event_envelope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('async_handlers', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('pending_handlers', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'RETRYING', 'COMPLETED', 'DEAD_LETTER', name='event_envelope_status_enum'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queue', sa.String(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_envelope_created_at', 'event_envelope', ['created_at'], unique=False)
    op.create_index('ix_event_envelope_queue_status_next_run_at', 'event_envelope', ['queue', 'status', 'next_run_at'], unique=False)
    op.create_index('ix_event_envelope_status_next_run_at', 'event_envelope', ['status', 'next_run_at'], unique=False)
    op.create_index('ix_event_envelope_updated_at', 'event_envelope', ['updated_at'], unique=False)
    op.create_table('leaderboard_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'FINALIZED', name='leaderboard_run_status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_start', 'period_end', name='uq_leaderboard_run')
    )
    op.create_index('ix_leaderboard_run_created_at', 'leaderboard_run', ['created_at'], unique=False)
    op.create_index('ix_leaderboard_run_status', 'leaderboard_run', ['status'], unique=False)
    op.create_index('ix_leaderboard_run_updated_at', 'leaderboard_run', ['updated_at'], unique=False)
    op.create_table('monthly_leaderboard_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('month', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    op.create_index('ix_monthly_leaderboard_notification_created_at', 'monthly_leaderboard_notification', ['created_at'], unique=False)
    op.create_index('ix_monthly_leaderboard_notification_updated_at', 'monthly_leaderboard_notification', ['updated_at'], unique=False)
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('ONE_TIME_PRICE', 'RECURRING_PRICE', name='plan_type_enum'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('boost_for_days', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('payment_frequency_count', sa.Integer(), nullable=True),
    sa.Column('payment_frequency_interval', sa.Enum('DAY', 'WEEK', 'MONTH', 'YEAR', name='time_interval_enum'), nullable=True),
    sa.Column('subscription_period_count', sa.Integer(), nullable=True),
    sa.Column('subscription_period_interval', sa.Enum('DAY', 'WEEK', 'MONTH', 'YEAR', name='time_interval_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_plan_created_at', 'plan', ['created_at'], unique=False)
    op.create_index('ix_plan_type', 'plan', ['type'], unique=False)
    op.create_index('ix_plan_updated_at', 'plan', ['updated_at'], unique=False)
    op.create_table('plan_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_plan_feature_created_at', 'plan_feature', ['created_at'], unique=False)
    op.create_index('ix_plan_feature_updated_at', 'plan_feature', ['updated_at'], unique=False)
    op.create_table('reward_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('ENGAGEMENT', 'STREAK', 'ADMIN', 'SYSTEM', 'BONUS', name='reward_rule_category_enum'), nullable=False),
    sa.Column('base_reward_amount', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=True),
    sa.Column('lifetime_cap', sa.Integer(), nullable=True),
    sa.Column('global_cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('per_target_cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('tier_config', sa.JSON(), nullable=True),
    sa.Column('admin_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_reward_rule_category', 'reward_rule', ['category'], unique=False)
    op.create_index('ix_reward_rule_is_active', 'reward_rule', ['is_active'], unique=False)
    op.create_index('ix_reward_rule_updated_at', 'reward_rule', ['updated_at'], unique=False)
    op.create_table('use_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_use_case_created_at', 'use_case', ['created_at'], unique=False)
    op.create_index('ix_use_case_updated_at', 'use_case', ['updated_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clerk_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('MEMBER', 'ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('role_intent', sa.String(), nullable=True),
    sa.Column('heard_from', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'TERMINATED', name='user_status_enum'), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_user_created_at', 'user', ['created_at'], unique=False)
    op.create_index('ix_user_heard_from', 'user', ['heard_from'], unique=False)
    op.create_index('ix_user_onboarded_at', 'user', ['onboarded_at'], unique=False)
    op.create_index('ix_user_role_intent', 'user', ['role_intent'], unique=False)
    op.create_index('ix_user_status', 'user', ['status'], unique=False)
    op.create_index('ix_user_updated_at', 'user', ['updated_at'], unique=False)
    op.create_table('alternative_product_category',
    sa.Column('alternative_product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alternative_product_id'], ['alternative_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alternative_product_id', 'category_id')
    )
    op.create_table('event_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('envelope_id', sa.Integer(), nullable=False),
    sa.Column('handler', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SUCCEEDED', 'FAILED', 'TIMED_OUT', name='event_attempt_status_enum'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['event_envelope.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_attempt_envelope_id_created_at', 'event_attempt', ['envelope_id', 'created_at'], unique=False)
    op.create_table('member_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'IN_REVIEW', 'CLOSED', name='feedback_status_enum'), nullable=False),
    sa.Column('admin_note', sa.String(), nullable=True),
    sa.Column('reward_eligible', sa.Boolean(), nullable=False),
    sa.Column('reward_granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_member_feedback_created_at', 'member_feedback', ['created_at'], unique=False)
    op.create_index('ix_member_feedback_updated_at', 'member_feedback', ['updated_at'], unique=False)
    op.create_index('ix_member_feedback_user_id_created_at', 'member_feedback', ['user_id', 'created_at'], unique=False)
    op.create_table('plan_feature_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_experimental', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['plan_feature.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'feature_id', name='uq_plan_feature_assignment')
    )
    op.create_index('ix_plan_feature_assignment_created_at', 'plan_feature_assignment', ['created_at'], unique=False)
    op.create_index('ix_plan_feature_assignment_enabled', 'plan_feature_assignment', ['enabled'], unique=False)
    op.create_index('ix_plan_feature_assignment_updated_at', 'plan_feature_assignment', ['updated_at'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('tagline', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('plan_assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('SAAS', 'BROWSER_EXTENSION', 'MOBILE_APP', 'DESKTOP_APP', 'API', 'OPEN_SOURCE', 'OTHER', name='product_type_enum'), nullable=False),
    sa.Column('pricing_model', sa.Enum('FREE', 'FREEMIUM', 'SUBSCRIPTION', 'ONE_TIME', 'CUSTOM', name='pricing_model_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='product_status_enum'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starting_price_cents', sa.Integer(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('banner_image', sa.String(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('platforms', postgresql.ARRAY(sa.Enum('WEB', 'IOS', 'ANDROID', 'MAC', 'WINDOWS', 'LINUX', 'CHROME_EXTENSION', 'FIREFOX_EXTENSION', name='platform_enum')), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('subscription_id')
    )
    op.create_index('ix_product_category_id_created_at', 'product', ['category_id', 'created_at'], unique=False)
    op.create_index('ix_product_created_at', 'product', ['created_at'], unique=False)
    op.create_index('ix_product_status_published_at', 'product', ['status', 'published_at'], unique=False)
    op.create_index('ix_product_updated_at', 'product', ['updated_at'], unique=False)
    op.create_table('reward_balance',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('lifetime_earned', sa.Integer(), nullable=False),
    sa.Column('lifetime_spent', sa.Integer(), nullable=False),
    sa.Column('lifetime_adjusted', sa.Integer(), nullable=False),
    sa.Column('lifetime_refunded', sa.Integer(), nullable=False),
    sa.Column('current_streak_count', sa.Integer(), nullable=False),
    sa.Column('longest_streak_count', sa.Integer(), nullable=False),
    sa.Column('current_streak_tier', sa.String(), nullable=True),
    sa.Column('streak_active_through', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_earned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_adjustment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_reward_balance_balance', 'reward_balance', ['balance'], unique=False)
    op.create_index('ix_reward_balance_updated_at', 'reward_balance', ['updated_at'], unique=False)
    op.create_table('reward_catalog_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feature_key', sa.String(), nullable=False),
    sa.Column('plan_feature_key', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('PLACEMENT', 'ANALYTICS', 'INSIGHTS', 'ACCESS', 'EXPOSURE', 'UTILITY', name='reward_feature_category_enum'), nullable=False),
    sa.Column('base_cost', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_active_per_user', sa.Integer(), nullable=True),
    sa.Column('max_pending_per_user', sa.Integer(), nullable=True),
    sa.Column('requires_product', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plan_feature_key'], ['plan_feature.key'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_key')
    )
    op.create_index('ix_reward_catalog_item_category', 'reward_catalog_item', ['category'], unique=False)
    op.create_index('ix_reward_catalog_item_is_active', 'reward_catalog_item', ['is_active'], unique=False)
    op.create_index('ix_reward_catalog_item_updated_at', 'reward_catalog_item', ['updated_at'], unique=False)
    op.create_table('site_traffic_browser_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('browser', sa.String(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'source', 'browser', name='uq_site_traffic_browser_daily')
    )
    op.create_index('ix_site_traffic_browser_daily_browser', 'site_traffic_browser_daily', ['browser'], unique=False)
    op.create_index('ix_site_traffic_browser_daily_date', 'site_traffic_browser_daily', ['date'], unique=False)
    op.create_table('site_traffic_city_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'source', 'city', 'region', 'country', 'country_code', name='uq_site_traffic_city_daily')
    )
    op.create_index('ix_site_traffic_city_daily_city', 'site_traffic_city_daily', ['city'], unique=False)
    op.create_index('ix_site_traffic_city_daily_date', 'site_traffic_city_daily', ['date'], unique=False)
    op.create_table('site_traffic_country_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'source', 'country', 'country_code', name='uq_site_traffic_country_daily')
    )
    op.create_index('ix_site_traffic_country_daily_country', 'site_traffic_country_daily', ['country'], unique=False)
    op.create_index('ix_site_traffic_country_daily_date', 'site_traffic_country_daily', ['date'], unique=False)
    op.create_table('site_traffic_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('bounce_rate', sa.Float(), nullable=False),
    sa.Column('average_session_duration', sa.Float(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('returning_visitors', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('pages_per_session', sa.Float(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'source', name='uq_site_traffic_daily')
    )
    op.create_index('ix_site_traffic_daily_date', 'site_traffic_daily', ['date'], unique=False)
    op.create_index('ix_site_traffic_daily_source_date', 'site_traffic_daily', ['source', 'date'], unique=False)
    op.create_table('site_traffic_device_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('device_category', sa.String(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'source', 'device_category', name='uq_site_traffic_device_daily')
    )
    op.create_index('ix_site_traffic_device_daily_date', 'site_traffic_device_daily', ['date'], unique=False)
    op.create_index('ix_site_traffic_device_daily_device_category', 'site_traffic_device_daily', ['device_category'], unique=False)
    op.create_table('site_traffic_operating_system_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('operating_system', sa.String(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'source', 'operating_system', name='uq_site_traffic_operating_system_daily')
    )
    op.create_index('ix_site_traffic_operating_system_daily_date', 'site_traffic_operating_system_daily', ['date'], unique=False)
    op.create_index('ix_site_traffic_operating_system_daily_operating_system', 'site_traffic_operating_system_daily', ['operating_system'], unique=False)
    op.create_table('site_traffic_referrer_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('referrer', sa.String(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'source', 'referrer', name='uq_site_traffic_referrer_daily')
    )
    op.create_index('ix_site_traffic_referrer_daily_date', 'site_traffic_referrer_daily', ['date'], unique=False)
    op.create_index('ix_site_traffic_referrer_daily_referrer', 'site_traffic_referrer_daily', ['referrer'], unique=False)
    op.create_table('site_traffic_region_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'source', 'region', 'country', 'country_code', name='uq_site_traffic_region_daily')
    )
    op.create_index('ix_site_traffic_region_daily_date', 'site_traffic_region_daily', ['date'], unique=False)
    op.create_index('ix_site_traffic_region_daily_region', 'site_traffic_region_daily', ['region'], unique=False)
    op.create_table('use_case_category',
    sa.Column('use_case_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['use_case_id'], ['use_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('use_case_id', 'category_id')
    )
    op.create_table('user_plan_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('user_id', 'plan_id', name='uq_user_plan_purchase')
    )
    op.create_index('ix_user_plan_purchase_created_at', 'user_plan_purchase', ['created_at'], unique=False)
    op.create_index('ix_user_plan_purchase_updated_at', 'user_plan_purchase', ['updated_at'], unique=False)
    op.create_table('payment_connector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('DODO', 'ABACATEPAY', 'POLAR', 'STRIPE', 'LEMONSQUEEZY', 'PADDLE', 'PAYSTACK', 'REVENUECAT', 'CREEM', name='payment_connector_provider_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'ERROR', name='payment_connector_status_enum'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_all_time_revenue_cents', sa.Integer(), nullable=True),
    sa.Column('latest_currency_code', sa.String(), nullable=True),
    sa.Column('latest_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', name='uq_payment_connector_product_id')
    )
    op.create_index('ix_payment_connector_product_id_updated_at', 'payment_connector', ['product_id', 'updated_at'], unique=False)
    op.create_index('ix_payment_connector_status_updated_at', 'payment_connector', ['status', 'updated_at'], unique=False)
    op.create_table('product_alternative_product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('alternative_product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alternative_product_id'], ['alternative_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'alternative_product_id')
    )
    op.create_table('product_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index('ix_product_analytics_created_at', 'product_analytics', ['created_at'], unique=False)
    op.create_index('ix_product_analytics_updated_at', 'product_analytics', ['updated_at'], unique=False)
    op.create_index('ix_product_analytics_upvotes', 'product_analytics', ['upvotes'], unique=False)
    op.create_table('product_badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('badge', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_badge_badge', 'product_badge', ['badge'], unique=False)
    op.create_index('ix_product_badge_created_at', 'product_badge', ['created_at'], unique=False)
    op.create_index('ix_product_badge_updated_at', 'product_badge', ['updated_at'], unique=False)
    op.create_table('product_claim_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('DNS', 'EMAIL_OTP', name='product_claim_method_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FULFILLED', 'EXPIRED', 'CANCELLED', 'FAILED', name='product_claim_status_enum'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('otp_hash', sa.String(), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_claim_attempt_product_id_status', 'product_claim_attempt', ['product_id', 'status'], unique=False)
    op.create_index('ix_product_claim_attempt_user_id_status', 'product_claim_attempt', ['user_id', 'status'], unique=False)
    op.create_table('product_leaderboard_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_components', sa.JSON(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['leaderboard_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'product_id', name='uq_product_leaderboard_score')
    )
    op.create_index('ix_product_leaderboard_score_created_at', 'product_leaderboard_score', ['created_at'], unique=False)
    op.create_index('ix_product_leaderboard_score_run_id_rank', 'product_leaderboard_score', ['run_id', 'rank'], unique=False)
    op.create_index('ix_product_leaderboard_score_run_id_score', 'product_leaderboard_score', ['run_id', 'score'], unique=False)
    op.create_index('ix_product_leaderboard_score_updated_at', 'product_leaderboard_score', ['updated_at'], unique=False)
    op.create_table('product_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_media_created_at', 'product_media', ['created_at'], unique=False)
    op.create_index('ix_product_media_updated_at', 'product_media', ['updated_at'], unique=False)
    op.create_table('product_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('twitter_url', sa.String(), nullable=True),
    sa.Column('demo_url', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('utm_campaign', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index('ix_product_metadata_created_at', 'product_metadata', ['created_at'], unique=False)
    op.create_index('ix_product_metadata_updated_at', 'product_metadata', ['updated_at'], unique=False)
    op.create_table('product_traffic_browser_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('browser', sa.String(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'date', 'source', 'browser', name='uq_product_traffic_browser_daily')
    )
    op.create_index('ix_product_traffic_browser_daily_browser', 'product_traffic_browser_daily', ['browser'], unique=False)
    op.create_index('ix_product_traffic_browser_daily_product_id_date', 'product_traffic_browser_daily', ['product_id', 'date'], unique=False)
    op.create_table('product_traffic_channel_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'date', 'source', 'channel', name='uq_product_traffic_channel_daily')
    )
    op.create_index('ix_product_traffic_channel_daily_channel', 'product_traffic_channel_daily', ['channel'], unique=False)
    op.create_index('ix_product_traffic_channel_daily_product_id_date', 'product_traffic_channel_daily', ['product_id', 'date'], unique=False)
    op.create_table('product_traffic_city_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'date', 'source', 'city', 'region', 'country', 'country_code', name='uq_product_traffic_city_daily')
    )
    op.create_index('ix_product_traffic_city_daily_city', 'product_traffic_city_daily', ['city'], unique=False)
    op.create_index('ix_product_traffic_city_daily_product_id_date', 'product_traffic_city_daily', ['product_id', 'date'], unique=False)
    op.create_table('product_traffic_country_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'date', 'source', 'country', 'country_code', name='uq_product_traffic_country_daily')
    )
    op.create_index('ix_product_traffic_country_daily_country', 'product_traffic_country_daily', ['country'], unique=False)
    op.create_index('ix_product_traffic_country_daily_product_id_date', 'product_traffic_country_daily', ['product_id', 'date'], unique=False)
    op.create_table('product_traffic_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('bounce_rate', sa.Float(), nullable=False),
    sa.Column('average_session_duration', sa.Float(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('returning_visitors', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('pages_per_session', sa.Float(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'date', 'source', name='uq_product_traffic_daily')
    )
    op.create_index('ix_product_traffic_daily_date', 'product_traffic_daily', ['date'], unique=False)
    op.create_index('ix_product_traffic_daily_product_id_date', 'product_traffic_daily', ['product_id', 'date'], unique=False)
    op.create_index('ix_product_traffic_daily_source_date', 'product_traffic_daily', ['source', 'date'], unique=False)
    op.create_table('product_traffic_device_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('device_category', sa.String(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'date', 'source', 'device_category', name='uq_product_traffic_device_daily')
    )
    op.create_index('ix_product_traffic_device_daily_device_category', 'product_traffic_device_daily', ['device_category'], unique=False)
    op.create_index('ix_product_traffic_device_daily_product_id_date', 'product_traffic_device_daily', ['product_id', 'date'], unique=False)
    op.create_table('product_traffic_operating_system_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('operating_system', sa.String(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'date', 'source', 'operating_system', name='uq_product_traffic_operating_system_daily')
    )
    op.create_index('ix_product_traffic_operating_system_daily_operating_system', 'product_traffic_operating_system_daily', ['operating_system'], unique=False)
    op.create_index('ix_product_traffic_operating_system_daily_product_id_date', 'product_traffic_operating_system_daily', ['product_id', 'date'], unique=False)
    op.create_table('product_traffic_referrer_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('GA4', name='analytics_data_source_enum'), nullable=False),
    sa.Column('referrer', sa.String(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['analytics_ingestion_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'date', 'source', 'referrer', name='uq_product_traffic_referrer_daily')
    )
    op.create_index('ix_product_traffic_referrer_daily_product_id_date', 'product_traffic_referrer_daily', ['product_id', 'date'], unique=False)
    op.create_index('ix_product_traffic_referrer_daily_referrer', 'product_traffic_referrer_daily', ['referrer'], unique=False)
    op.create_table('product_upvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'user_id', name='uq_product_upvote')
    )
    op.create_index('ix_product_upvote_created_at', 'product_upvote', ['created_at'], unique=False)
    op.create_index('ix_product_upvote_user_id', 'product_upvote', ['user_id'], unique=False)
    op.create_table('product_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('verification_txt', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backlink_is_verified', sa.Boolean(), nullable=False),
    sa.Column('backlink_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backlink_last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backlink_found_url', sa.String(), nullable=True),
    sa.Column('backlink_last_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index('ix_product_verification_created_at', 'product_verification', ['created_at'], unique=False)
    op.create_index('ix_product_verification_updated_at', 'product_verification', ['updated_at'], unique=False)
    op.create_table('redemption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELED', 'FAILED', 'REFUNDED', name='redemption_status_enum'), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('original_cost', sa.Integer(), nullable=False),
    sa.Column('refunded_rewards', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['feature_key'], ['reward_catalog_item.feature_key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_redemption_created_at', 'redemption', ['created_at'], unique=False)
    op.create_index('ix_redemption_feature_key', 'redemption', ['feature_key'], unique=False)
    op.create_index('ix_redemption_product_id', 'redemption', ['product_id'], unique=False)
    op.create_index('ix_redemption_user_id_status', 'redemption', ['user_id', 'status'], unique=False)
    op.create_table('feature_entitlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(), nullable=False),
    sa.Column('redemption_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('subject_type', sa.Enum('USER', 'PRODUCT', 'GLOBAL', name='feature_subject_type_enum'), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'PAUSED', 'EXPIRED', 'CANCELED', 'FAILED', name='feature_entitlement_status_enum'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['feature_key'], ['reward_catalog_item.feature_key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['redemption_id'], ['redemption.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feature_entitlement_feature_status', 'feature_entitlement', ['feature_key', 'status'], unique=False)
    op.create_index('ix_feature_entitlement_product_status', 'feature_entitlement', ['product_id', 'status'], unique=False)
    op.create_index('ix_feature_entitlement_subject', 'feature_entitlement', ['subject_type', 'subject_id'], unique=False)
    op.create_index('ix_feature_entitlement_user_feature_status', 'feature_entitlement', ['user_id', 'feature_key', 'status'], unique=False)
    op.create_table('payment_connector_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='payment_credential_status_enum'), nullable=False),
    sa.Column('encryption_version', sa.Integer(), nullable=False),
    sa.Column('encrypted_key', sa.String(), nullable=False),
    sa.Column('key_hint', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['payment_connector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_connector_credential_connector_id_status', 'payment_connector_credential', ['connector_id', 'status'], unique=False)
    op.create_index('ix_payment_connector_credential_created_at', 'payment_connector_credential', ['created_at'], unique=False)
    op.create_table('payment_revenue_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_revenue_cents', sa.Integer(), nullable=False),
    sa.Column('all_time_revenue_cents', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['payment_connector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'period_start', 'currency_code', name='uq_payment_revenue_snapshot')
    )
    op.create_index('ix_payment_revenue_snapshot_connector_id_period_start', 'payment_revenue_snapshot', ['connector_id', 'period_start'], unique=False)
    op.create_index('ix_payment_revenue_snapshot_created_at', 'payment_revenue_snapshot', ['created_at'], unique=False)
    op.create_table('reward_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EARN', 'SPEND', 'ADJUSTMENT', 'REFUND', name='reward_transaction_type_enum'), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('rule_key', sa.String(), nullable=True),
    sa.Column('reward_key', sa.String(), nullable=True),
    sa.Column('redemption_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('event_hash', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('acted_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acted_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['redemption_id'], ['redemption.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reward_key'], ['reward_catalog_item.feature_key'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['reward_rule.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash', name='uq_reward_transaction_event_hash')
    )
    op.create_index('ix_reward_transaction_event_id', 'reward_transaction', ['event_id'], unique=False)
    op.create_index('ix_reward_transaction_product_id', 'reward_transaction', ['product_id'], unique=False)
    op.create_index('ix_reward_transaction_reward_key', 'reward_transaction', ['reward_key'], unique=False)
    op.create_index('ix_reward_transaction_rule_key', 'reward_transaction', ['rule_key'], unique=False)
    op.create_index('ix_reward_transaction_type', 'reward_transaction', ['type'], unique=False)
    op.create_index('ix_reward_transaction_user_id_created_at', 'reward_transaction', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_reward_transaction_user_rule_target_type_created_at', 'reward_transaction', ['user_id', 'rule_key', 'target_id', 'type', 'created_at'], unique=False)
    op.create_index('ix_reward_transaction_user_rule_type_created_at', 'reward_transaction', ['user_id', 'rule_key', 'type', 'created_at'], unique=False)
    op.create_table('placement_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entitlement_id', sa.Integer(), nullable=False),
    sa.Column('redemption_id', sa.Integer(), nullable=True),
    sa.Column('feature_key', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('slot_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELED', 'FAILED', name='placement_status_enum'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activation_job_id', sa.String(), nullable=True),
    sa.Column('deactivation_job_id', sa.String(), nullable=True),
    sa.Column('inventory_token', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['entitlement_id'], ['feature_entitlement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_key'], ['reward_catalog_item.feature_key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['redemption_id'], ['redemption.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_placement_schedule_feature_key_status', 'placement_schedule', ['feature_key', 'status'], unique=False)
    op.create_index('ix_placement_schedule_product_id_starts_at', 'placement_schedule', ['product_id', 'starts_at'], unique=False)
    op.create_index('ix_placement_schedule_slot_key_starts_at', 'placement_schedule', ['slot_key', 'starts_at'], unique=False)
    op.create_index('ix_placement_schedule_status', 'placement_schedule', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_placement_schedule_status', table_name='placement_schedule')
    op.drop_index('ix_placement_schedule_slot_key_starts_at', table_name='placement_schedule')
    op.drop_index('ix_placement_schedule_product_id_starts_at', table_name='placement_schedule')
    op.drop_index('ix_placement_schedule_feature_key_status', table_name='placement_schedule')
    op.drop_table('placement_schedule')
    op.drop_index('ix_reward_transaction_user_rule_type_created_at', table_name='reward_transaction')
    op.drop_index('ix_reward_transaction_user_rule_target_type_created_at', table_name='reward_transaction')
    op.drop_index('ix_reward_transaction_user_id_created_at', table_name='reward_transaction')
    op.drop_index('ix_reward_transaction_type', table_name='reward_transaction')
    op.drop_index('ix_reward_transaction_rule_key', table_name='reward_transaction')
    op.drop_index('ix_reward_transaction_reward_key', table_name='reward_transaction')
    op.drop_index('ix_reward_transaction_product_id', table_name='reward_transaction')
    op.drop_index('ix_reward_transaction_event_id', table_name='reward_transaction')
    op.drop_table('reward_transaction')
    op.drop_index('ix_payment_revenue_snapshot_created_at', table_name='payment_revenue_snapshot')
    op.drop_index('ix_payment_revenue_snapshot_connector_id_period_start', table_name='payment_revenue_snapshot')
    op.drop_table('payment_revenue_snapshot')
    op.drop_index('ix_payment_connector_credential_created_at', table_name='payment_connector_credential')
    op.drop_index('ix_payment_connector_credential_connector_id_status', table_name='payment_connector_credential')
    op.drop_table('payment_connector_credential')
    op.drop_index('ix_feature_entitlement_user_feature_status', table_name='feature_entitlement')
    op.drop_index('ix_feature_entitlement_subject', table_name='feature_entitlement')
    op.drop_index('ix_feature_entitlement_product_status', table_name='feature_entitlement')
    op.drop_index('ix_feature_entitlement_feature_status', table_name='feature_entitlement')
    op.drop_table('feature_entitlement')
    op.drop_index('ix_redemption_user_id_status', table_name='redemption')
    op.drop_index('ix_redemption_product_id', table_name='redemption')
    op.drop_index('ix_redemption_feature_key', table_name='redemption')
    op.drop_index('ix_redemption_created_at', table_name='redemption')
    op.drop_table('redemption')
    op.drop_index('ix_product_verification_updated_at', table_name='product_verification')
    op.drop_index('ix_product_verification_created_at', table_name='product_verification')
    op.drop_table('product_verification')
    op.drop_index('ix_product_upvote_user_id', table_name='product_upvote')
    op.drop_index('ix_product_upvote_created_at', table_name='product_upvote')
    op.drop_table('product_upvote')
    op.drop_index('ix_product_traffic_referrer_daily_referrer', table_name='product_traffic_referrer_daily')
    op.drop_index('ix_product_traffic_referrer_daily_product_id_date', table_name='product_traffic_referrer_daily')
    op.drop_table('product_traffic_referrer_daily')
    op.drop_index('ix_product_traffic_operating_system_daily_product_id_date', table_name='product_traffic_operating_system_daily')
    op.drop_index('ix_product_traffic_operating_system_daily_operating_system', table_name='product_traffic_operating_system_daily')
    op.drop_table('product_traffic_operating_system_daily')
    op.drop_index('ix_product_traffic_device_daily_product_id_date', table_name='product_traffic_device_daily')
    op.drop_index('ix_product_traffic_device_daily_device_category', table_name='product_traffic_device_daily')
    op.drop_table('product_traffic_device_daily')
    op.drop_index('ix_product_traffic_daily_source_date', table_name='product_traffic_daily')
    op.drop_index('ix_product_traffic_daily_product_id_date', table_name='product_traffic_daily')
    op.drop_index('ix_product_traffic_daily_date', table_name='product_traffic_daily')
    op.drop_table('product_traffic_daily')
    op.drop_index('ix_product_traffic_country_daily_product_id_date', table_name='product_traffic_country_daily')
    op.drop_index('ix_product_traffic_country_daily_country', table_name='product_traffic_country_daily')
    op.drop_table('product_traffic_country_daily')
    op.drop_index('ix_product_traffic_city_daily_product_id_date', table_name='product_traffic_city_daily')
    op.drop_index('ix_product_traffic_city_daily_city', table_name='product_traffic_city_daily')
    op.drop_table('product_traffic_city_daily')
    op.drop_index('ix_product_traffic_channel_daily_product_id_date', table_name='product_traffic_channel_daily')
    op.drop_index('ix_product_traffic_channel_daily_channel', table_name='product_traffic_channel_daily')
    op.drop_table('product_traffic_channel_daily')
    op.drop_index('ix_product_traffic_browser_daily_product_id_date', table_name='product_traffic_browser_daily')
    op.drop_index('ix_product_traffic_browser_daily_browser', table_name='product_traffic_browser_daily')
    op.drop_table('product_traffic_browser_daily')
    op.drop_index('ix_product_metadata_updated_at', table_name='product_metadata')
    op.drop_index('ix_product_metadata_created_at', table_name='product_metadata')
    op.drop_table('product_metadata')
    op.drop_index('ix_product_media_updated_at', table_name='product_media')
    op.drop_index('ix_product_media_created_at', table_name='product_media')
    op.drop_table('product_media')
    op.drop_index('ix_product_leaderboard_score_updated_at', table_name='product_leaderboard_score')
    op.drop_index('ix_product_leaderboard_score_run_id_score', table_name='product_leaderboard_score')
    op.drop_index('ix_product_leaderboard_score_run_id_rank', table_name='product_leaderboard_score')
    op.drop_index('ix_product_leaderboard_score_created_at', table_name='product_leaderboard_score')
    op.drop_table('product_leaderboard_score')
    op.drop_index('ix_product_claim_attempt_user_id_status', table_name='product_claim_attempt')
    op.drop_index('ix_product_claim_attempt_product_id_status', table_name='product_claim_attempt')
    op.drop_table('product_claim_attempt')
    op.drop_index('ix_product_badge_updated_at', table_name='product_badge')
    op.drop_index('ix_product_badge_created_at', table_name='product_badge')
    op.drop_index('ix_product_badge_badge', table_name='product_badge')
    op.drop_table('product_badge')
    op.drop_index('ix_product_analytics_upvotes', table_name='product_analytics')
    op.drop_index('ix_product_analytics_updated_at', table_name='product_analytics')
    op.drop_index('ix_product_analytics_created_at', table_name='product_analytics')
    op.drop_table('product_analytics')
    op.drop_table('product_alternative_product')
    op.drop_index('ix_payment_connector_status_updated_at', table_name='payment_connector')
    op.drop_index('ix_payment_connector_product_id_updated_at', table_name='payment_connector')
    op.drop_table('payment_connector')
    op.drop_index('ix_user_plan_purchase_updated_at', table_name='user_plan_purchase')
    op.drop_index('ix_user_plan_purchase_created_at', table_name='user_plan_purchase')
    op.drop_table('user_plan_purchase')
    op.drop_table('use_case_category')
    op.drop_index('ix_site_traffic_region_daily_region', table_name='site_traffic_region_daily')
    op.drop_index('ix_site_traffic_region_daily_date', table_name='site_traffic_region_daily')
    op.drop_table('site_traffic_region_daily')
    op.drop_index('ix_site_traffic_referrer_daily_referrer', table_name='site_traffic_referrer_daily')
    op.drop_index('ix_site_traffic_referrer_daily_date', table_name='site_traffic_referrer_daily')
    op.drop_table('site_traffic_referrer_daily')
    op.drop_index('ix_site_traffic_operating_system_daily_operating_system', table_name='site_traffic_operating_system_daily')
    op.drop_index('ix_site_traffic_operating_system_daily_date', table_name='site_traffic_operating_system_daily')
    op.drop_table('site_traffic_operating_system_daily')
    op.drop_index('ix_site_traffic_device_daily_device_category', table_name='site_traffic_device_daily')
    op.drop_index('ix_site_traffic_device_daily_date', table_name='site_traffic_device_daily')
    op.drop_table('site_traffic_device_daily')
    op.drop_index('ix_site_traffic_daily_source_date', table_name='site_traffic_daily')
    op.drop_index('ix_site_traffic_daily_date', table_name='site_traffic_daily')
    op.drop_table('site_traffic_daily')
    op.drop_index('ix_site_traffic_country_daily_date', table_name='site_traffic_country_daily')
    op.drop_index('ix_site_traffic_country_daily_country', table_name='site_traffic_country_daily')
    op.drop_table('site_traffic_country_daily')
    op.drop_index('ix_site_traffic_city_daily_date', table_name='site_traffic_city_daily')
    op.drop_index('ix_site_traffic_city_daily_city', table_name='site_traffic_city_daily')
    op.drop_table('site_traffic_city_daily')
    op.drop_index('ix_site_traffic_browser_daily_date', table_name='site_traffic_browser_daily')
    op.drop_index('ix_site_traffic_browser_daily_browser', table_name='site_traffic_browser_daily')
    op.drop_table('site_traffic_browser_daily')
    op.drop_index('ix_reward_catalog_item_updated_at', table_name='reward_catalog_item')
    op.drop_index('ix_reward_catalog_item_is_active', table_name='reward_catalog_item')
    op.drop_index('ix_reward_catalog_item_category', table_name='reward_catalog_item')
    op.drop_table('reward_catalog_item')
    op.drop_index('ix_reward_balance_updated_at', table_name='reward_balance')
    op.drop_index('ix_reward_balance_balance', table_name='reward_balance')
    op.drop_table('reward_balance')
    op.drop_index('ix_product_updated_at', table_name='product')
    op.drop_index('ix_product_status_published_at', table_name='product')
    op.drop_index('ix_product_created_at', table_name='product')
    op.drop_index('ix_product_category_id_created_at', table_name='product')
    op.drop_table('product')
    op.drop_index('ix_plan_feature_assignment_updated_at', table_name='plan_feature_assignment')
    op.drop_index('ix_plan_feature_assignment_enabled', table_name='plan_feature_assignment')
    op.drop_index('ix_plan_feature_assignment_created_at', table_name='plan_feature_assignment')
    op.drop_table('plan_feature_assignment')
    op.drop_index('ix_member_feedback_user_id_created_at', table_name='member_feedback')
    op.drop_index('ix_member_feedback_updated_at', table_name='member_feedback')
    op.drop_index('ix_member_feedback_created_at', table_name='member_feedback')
    op.drop_table('member_feedback')
    op.drop_index('ix_event_attempt_envelope_id_created_at', table_name='event_attempt')
    op.drop_table('event_attempt')
    op.drop_table('alternative_product_category')
    op.drop_index('ix_user_updated_at', table_name='user')
    op.drop_index('ix_user_status', table_name='user')
    op.drop_index('ix_user_role_intent', table_name='user')
    op.drop_index('ix_user_onboarded_at', table_name='user')
    op.drop_index('ix_user_heard_from', table_name='user')
    op.drop_index('ix_user_created_at', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_use_case_updated_at', table_name='use_case')
    op.drop_index('ix_use_case_created_at', table_name='use_case')
    op.drop_table('use_case')
    op.drop_index('ix_reward_rule_updated_at', table_name='reward_rule')
    op.drop_index('ix_reward_rule_is_active', table_name='reward_rule')
    op.drop_index('ix_reward_rule_category', table_name='reward_rule')
    op.drop_table('reward_rule')
    op.drop_index('ix_plan_feature_updated_at', table_name='plan_feature')
    op.drop_index('ix_plan_feature_created_at', table_name='plan_feature')
    op.drop_table('plan_feature')
    op.drop_index('ix_plan_updated_at', table_name='plan')
    op.drop_index('ix_plan_type', table_name='plan')
    op.drop_index('ix_plan_created_at', table_name='plan')
    op.drop_table('plan')
    op.drop_index('ix_monthly_leaderboard_notification_updated_at', table_name='monthly_leaderboard_notification')
    op.drop_index('ix_monthly_leaderboard_notification_created_at', table_name='monthly_leaderboard_notification')
    op.drop_table('monthly_leaderboard_notification')
    op.drop_index('ix_leaderboard_run_updated_at', table_name='leaderboard_run')
    op.drop_index('ix_leaderboard_run_status', table_name='leaderboard_run')
    op.drop_index('ix_leaderboard_run_created_at', table_name='leaderboard_run')
    op.drop_table('leaderboard_run')
    op.drop_index('ix_event_envelope_updated_at', table_name='event_envelope')
    op.drop_index('ix_event_envelope_status_next_run_at', table_name='event_envelope')
    op.drop_index('ix_event_envelope_queue_status_next_run_at', table_name='event_envelope')
    op.drop_index('ix_event_envelope_created_at', table_name='event_envelope')
    op.drop_table('event_envelope')
    op.drop_index('ix_category_updated_at', table_name='category')
    op.drop_index('ix_category_created_at', table_name='category')
    op.drop_table('category')
    op.drop_index('ix_analytics_ingestion_run_window_start_end', table_name='analytics_ingestion_run')
    op.drop_index('ix_analytics_ingestion_run_status_created_at', table_name='analytics_ingestion_run')
    op.drop_index('ix_analytics_ingestion_run_job_source_window_start', table_name='analytics_ingestion_run')
    op.drop_table('analytics_ingestion_run')
    op.drop_index('ix_alternative_product_updated_at', table_name='alternative_product')
    op.drop_index('ix_alternative_product_created_at', table_name='alternative_product')
    op.drop_table('alternative_product')
    # ### end Alembic commands ###
