"""init

Revision ID: 2665c59a46d6
Revises: 
Create Date: 2026-01-22 03:10:39.094093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2665c59a46d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clerk_id', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('MEMBER', 'ADMIN', name='user_role_enum'), server_default=sa.text("'MEMBER'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id'),
    sa.UniqueConstraint('handle')
    )
    op.create_index('ix_user_handle', 'user', ['handle'], unique=False)
    op.create_table('provider_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', name='provider_enum'), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('provider_username', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISCONNECTED', name='provider_status_enum'), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_account_provider_user_id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_provider_account_user_provider')
    )
    op.create_index('ix_provider_account_user_id', 'provider_account', ['user_id'], unique=False)
    op.create_table('provider_installation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', name='provider_enum'), nullable=False),
    sa.Column('installation_id', sa.String(), nullable=False),
    sa.Column('account_login', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'installation_id', name='uq_provider_installation_provider_installation_id')
    )
    op.create_index('ix_provider_installation_user_id', 'provider_installation', ['user_id'], unique=False)
    op.create_table('score_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('scoring_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', 'period_start', 'period_end', name='uq_score_snapshot_user_period_start_end')
    )
    op.create_index('ix_score_snapshot_period_start', 'score_snapshot', ['period', 'period_start'], unique=False)
    op.create_index('ix_score_snapshot_user_period', 'score_snapshot', ['user_id', 'period'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='task_status_enum'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type', 'dedupe_key', name='uq_task_type_dedupe')
    )
    op.create_index('ix_task_locked_until', 'task', ['locked_until'], unique=False)
    op.create_index('ix_task_status_run_after', 'task', ['status', 'run_after'], unique=False)
    op.create_index('ix_task_type', 'task', ['task_type'], unique=False)
    op.create_index('ix_task_user_id', 'task', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_public', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('include_in_leaderboard', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('show_repos', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('show_commits', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_settings_user_id')
    )
    op.create_index('ix_user_settings_country', 'user_settings', ['country'], unique=False)
    op.create_index('ix_user_settings_user_id', 'user_settings', ['user_id'], unique=False)
    op.create_table('activity_fact_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', name='provider_enum'), nullable=False),
    sa.Column('provider_account_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('bucket', sa.String(), server_default=sa.text("'global'"), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['provider_account_id'], ['provider_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'day', 'metric_key', 'bucket', name='uq_activity_fact_daily_user_provider_day_metric_bucket')
    )
    op.create_index('ix_activity_fact_daily_provider_metric', 'activity_fact_daily', ['provider', 'metric_key'], unique=False)
    op.create_index('ix_activity_fact_daily_user_day', 'activity_fact_daily', ['user_id', 'day'], unique=False)
    op.create_table('leaderboard_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('scope', sa.String(), server_default=sa.text("'global'"), nullable=False),
    sa.Column('scope_metadata', sa.JSON(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['score_snapshot_id'], ['score_snapshot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', 'period_start', 'period_end', 'scope', name='uq_leaderboard_entry_user_period_scope')
    )
    op.create_index('ix_leaderboard_entry_scope_period_rank', 'leaderboard_entry', ['scope', 'period', 'period_start', 'rank'], unique=False)
    op.create_index('ix_leaderboard_entry_scope_period_score', 'leaderboard_entry', ['scope', 'period', 'period_start', 'total_score'], unique=False)
    op.create_index('ix_leaderboard_entry_user_period', 'leaderboard_entry', ['user_id', 'period', 'period_start'], unique=False)
    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', name='provider_enum'), nullable=False),
    sa.Column('provider_repo_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_login', sa.String(), nullable=False),
    sa.Column('primary_language', sa.String(), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['installation_id'], ['provider_installation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_repo_id', name='uq_repository_provider_repo_id')
    )
    op.create_index('ix_repository_full_name', 'repository', ['full_name'], unique=False)
    op.create_index('ix_repository_owner_login', 'repository', ['owner_login'], unique=False)
    op.create_index('ix_repository_primary_language', 'repository', ['primary_language'], unique=False)
    op.create_table('sync_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', name='provider_enum'), nullable=False),
    sa.Column('provider_installation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repos', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('facts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('warnings', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['provider_installation_id'], ['provider_installation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_run_provider_started', 'sync_run', ['provider', 'started_at'], unique=False)
    op.create_index('ix_sync_run_user_started', 'sync_run', ['user_id', 'started_at'], unique=False)
    op.create_table('activity_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', name='provider_enum'), nullable=False),
    sa.Column('provider_account_id', sa.Integer(), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('provider_item_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repo_full_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['provider_account_id'], ['provider_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'provider_item_id', name='uq_activity_item_user_provider_item')
    )
    op.create_index('ix_activity_item_user_occurred', 'activity_item', ['user_id', 'occurred_at'], unique=False)
    op.create_table('repo_sync_cursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', name='provider_enum'), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('cursor_key', sa.String(), nullable=False),
    sa.Column('cursor_value', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repository_id', 'cursor_key', name='uq_repo_sync_cursor_user_repo_cursor')
    )
    op.create_index('ix_repo_sync_cursor_user_cursor', 'repo_sync_cursor', ['user_id', 'cursor_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repo_sync_cursor_user_cursor', table_name='repo_sync_cursor')
    op.drop_table('repo_sync_cursor')
    op.drop_index('ix_activity_item_user_occurred', table_name='activity_item')
    op.drop_table('activity_item')
    op.drop_index('ix_sync_run_user_started', table_name='sync_run')
    op.drop_index('ix_sync_run_provider_started', table_name='sync_run')
    op.drop_table('sync_run')
    op.drop_index('ix_repository_primary_language', table_name='repository')
    op.drop_index('ix_repository_owner_login', table_name='repository')
    op.drop_index('ix_repository_full_name', table_name='repository')
    op.drop_table('repository')
    op.drop_index('ix_leaderboard_entry_user_period', table_name='leaderboard_entry')
    op.drop_index('ix_leaderboard_entry_scope_period_score', table_name='leaderboard_entry')
    op.drop_index('ix_leaderboard_entry_scope_period_rank', table_name='leaderboard_entry')
    op.drop_table('leaderboard_entry')
    op.drop_index('ix_activity_fact_daily_user_day', table_name='activity_fact_daily')
    op.drop_index('ix_activity_fact_daily_provider_metric', table_name='activity_fact_daily')
    op.drop_table('activity_fact_daily')
    op.drop_index('ix_user_settings_user_id', table_name='user_settings')
    op.drop_index('ix_user_settings_country', table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index('ix_task_user_id', table_name='task')
    op.drop_index('ix_task_type', table_name='task')
    op.drop_index('ix_task_status_run_after', table_name='task')
    op.drop_index('ix_task_locked_until', table_name='task')
    op.drop_table('task')
    op.drop_index('ix_score_snapshot_user_period', table_name='score_snapshot')
    op.drop_index('ix_score_snapshot_period_start', table_name='score_snapshot')
    op.drop_table('score_snapshot')
    op.drop_index('ix_provider_installation_user_id', table_name='provider_installation')
    op.drop_table('provider_installation')
    op.drop_index('ix_provider_account_user_id', table_name='provider_account')
    op.drop_table('provider_account')
    op.drop_index('ix_user_handle', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
