name: Tests
on:
  pull_request: null
  push:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref_name }}-${{ github.actor }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  unit:
    uses: abhi1693/actions/.github/workflows/node-ci.yml@34e92ba1eee6a47e9b10f13e2180114fc01b6027
    with:
      checks: '["test"]'
      scripts: '{"test": "test:ci"}'
      timeout-minutes: 10
      runs-on: ubuntu-24.04-arm
      node-version: '22'
      enable-cache: false
      ignore-scripts: true
      legacy-peer-deps: true
